### ISSUE TITLE
escape_filter_chars changed behavior

### ISSUE THREAD

**Issue by TWAC** [cannatag/ldap3#216]
I am using escape_filter_chars while building a search_filter.
Upgrading from 1.3.3 to 1.4.0 makes some of my searches fail.
In 1.3.3 `escape_filter_chars("åäö") == "åäö"`
In 1.4.0 `escape_filter_chars("åäö") == "\\xe5\\xe4\\xf6"`

I do not quite understand the change concerning valid UTF-8, str does not have an encoding, and it is not possible to use the function with bytes.

**Comment by cannatag** [comment]
HI, which version of Python are you using? In 1.4.0 I followed the LDAP RFCs that states that every character > 0x7F must be escaped in filters. Have you tried to specify the characters as unicode?

**Comment by TWAC** [comment]
I am using Python 3.4.4.

Strings are already unicode on Python 3, so the result is the same.
```
>>> escape_filter_chars(u"åäö")
'\\xe5\\xe4\\xf6'
```

Sending UTF-8 to the function fails
```
>>> escape_filter_chars(u"åäö".encode("UTF-8"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\ldap3\utils\conv.py", line 55, in escape_filter_chars
    output = text.replace('\\', r'\5c')
TypeError: 'str' does not support the buffer interface
```

Besides '\\xe5\\xe4\\xf6' looks a lot like latin1, and not UTF-8
```
>>> binascii.hexlify(u'åäö'.encode('latin1'))
b'e5e4f6'
>>> binascii.hexlify(u'åäö'.encode('UTF-8'))
b'c3a5c3a4c3b6'
```

Is it this quote from RFC 4515 that is the problem? Will not some other part of ldap3 take care of creating UTF-8 from a search_filter?
```
   As indicated by the <valueencoding> rule, implementations MUST escape
   all octets greater than 0x7F that are not part of a valid UTF-8
   encoding sequence when they generate a string representation of a
   search filter.
```

**Comment by cannatag** [comment]
Hi,
I think you're right. Will check it as soon as possible.

**Comment by cannatag** [comment]
Hi TWAC,
I think the correct representation for u"åäö" is "\\c3\\a5\\c3\\a4\\c3\\b6". This is not a utf-8 representation, but is the result of the LDAP filter escaping mechanism described in RFC4515. 

I've changed the escape_filter_chars to use the default input encoding of the platform where the library runs or to use a specified one. In your case it should choose  "latin-1".

Can you give a try to the code in dev?

**Comment by TWAC** [comment]
Getting dev to run required some adjustments of my code.

I used to be able to log in like this.
```python
server = Server("local.domain.name", port=636, use_ssl=True, get_info=ALL)
conn = Connection(server, auto_bind=True, client_strategy=SYNC, user="TWAC@local.domain.name", password=getpass(), authentication=SIMPLE)
```

But it fails.
```
Traceback (most recent call last):
  File "C:\Users\TWAC\escapetest.py", line 8, in <module>
    conn = Connection(server, auto_bind=True, client_strategy=SYNC, user="TWAC@local.domain.name", password=getpass(), authentication=SIMPLE)
  File "C:\Python34\lib\site-packages\ldap3\core\connection.py", line 275, in __init__
    self.user = safe_dn(self.user)
  File "C:\Python34\lib\site-packages\ldap3\utils\dn.py", line 314, in safe_dn
    for component in parse_dn(dn, escape=True):
  File "C:\Python34\lib\site-packages\ldap3\utils\dn.py", line 284, in parse_dn
    if not validate_attribute_type(attribute_type):
  File "C:\Python34\lib\site-packages\ldap3\utils\dn.py", line 156, in validate_attribute_type
    raise LDAPInvalidDnError('attribute type not present')
ldap3.core.exceptions.LDAPInvalidDnError: attribute type not present
```

So I switched to NTLM, that login works.
```python
server = Server("local.domain.name", port=636, use_ssl=True, get_info=ALL)
conn = Connection(server, auto_bind=True, client_strategy=SYNC, user="local.domain.name\\TWAC", password=getpass(), authentication=NTLM)
base = "OU=Users,DC=local,DC=domain,DC=name"
qfilter = "(CN=%s)" % escape_filter_chars("Usér")
result = conn.search(search_base=base, search_scope=SUBTREE, search_filter=qfilter, attributes=ALL_ATTRIBUTES)
print(conn.response[0]["attributes"])
```

But I hit an encode error (the code works on 1.3.3).
```
Traceback (most recent call last):
  File "C:\Users\TWAC\escapetest.py", line 11, in <module>
    result = conn.search(search_base=base, search_scope=SUBTREE, search_filter=qfilter, attributes=ALL_ATTRIBUTES)
  File "C:\Python34\lib\site-packages\ldap3\core\connection.py", line 720, in search
    request = search_operation(search_base, search_filter, search_scope, dereference_aliases, attributes, size_limit, time_limit, types_only, self.server.schema if self.server else None)
  File "C:\Python34\lib\site-packages\ldap3\operation\search.py", line 357, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "C:\Python34\lib\site-packages\ldap3\operation\search.py", line 198, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema))
  File "C:\Python34\lib\site-packages\ldap3\operation\search.py", line 160, in evaluate_match
    assertion = {'attr': left_part, 'value': validate_assertion_value(schema, left_part, right_part)}
  File "C:\Python34\lib\site-packages\ldap3\protocol\convert.py", line 139, in validate_assertion_value
    validated_value += value[pos].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by cannatag** [comment]
Hi, the problem is with the AD naming convention that doesn't follow the LDAP RFCs. In version 2 of ldap3 I'm adding more checking on the input values to the LDAP operation (following the RFC directives). For Simple Bind Authentication only DN syntax is allowed (i.e. cn=name,ou=dep,o=organization). I've relaxed the check function to include also the "name@domain" and "domain\\name" (only for NTLM). Can you check the version in dev now?

**Comment by TWAC** [comment]
Yes, my original code works again :)
Thank you for your help.

**Comment by cannatag** [comment]
Released in 2.0.7.
