### ISSUE TITLE
Problem after upgrading to v2.5.1: AttributeError: 'NoneType' object has no attribute 'object_classes'

### ISSUE THREAD

**Issue by hogneh** [cannatag/ldap3#617]
Hi

After upgrading from ldap3 2.4.1 to ldap3 2.5.1 I'm having a problem with _schema being None in my ObjectDef (paths truncated):

```
  ...
  File "<djangoapp>/libs/ldap/entities.py", line 268, in __init__
    reader.search()
  File "<venv>/lib/python3.6/site-packages/ldap3/abstract/cursor.py", line 620, in search
    self._execute_query(query_scope, attributes)
  File "<venv>/lib/python3.6/site-packages/ldap3/abstract/cursor.py", line 369, in _execute_query
    self.definition._populate_attr_defs(object_class)
  File "<venv>/lib/python3.6/site-packages/ldap3/abstract/objectDef.py", line 103, in _populate_attr_defs
    if object_name in self._schema.object_classes:
AttributeError: 'NoneType' object has no attribute 'object_classes'
```
I'm using manually defined AttrDefs, so not sending in any server or connection object:
```
person_attributes = [AttrDef(...), ...]
person_object = ObjectDef('inetOrgPerson')
person_object += person_attributes
...
reader = Reader(connection=self.conn, object_def=self.person_object, query=search_filter, base=self.base)
reader.search()
```

**Comment by cannatag** [comment]
Hi, I'm unable to replicate this issue, can you give more information?

**Comment by hogneh** [comment]
When trying to create a minimal reproducible case I found the code that caused the issue.

In my code I had the following:
AttrDef('objectClass', description='LDAP Objectclasses', default=[])

Ldap3 v2.4.1 didn't mind, but this breaks with ldap3 2.5.1.

Not sure if it's a bug really, it doesn't make much sense to have that line and removing it fixes the issue.

**Comment by cannatag** [comment]
Ok, thanks. This should be fixed in the next release of ldap3.
