### ISSUE TITLE
LDAPSocketSendError in threaded web server

### ISSUE THREAD

**Issue by jaraco** [cannatag/ldap3#257]
Possibly related to #221, we're trying to update our web server to work with ldap3 2.1.0. When I invoke our code in a synchronous manner, it works fine, but when I run the threaded web server (cherrypy) and invoke a simple search though the web server, it raises an exception:

`LDAPSocketSendError: socket sending error[Errno 104] Connection reset by peer`

the exception seems to vary too. Other times it's:

`LDAPSocketSendError: socket sending error[Errno 1] _ssl.c:1312: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry`

or

`LDAPSocketSendError: socket sending error[Errno 32] Broken pipe`

So it seems that something new to ldap3 2.x socket handling no longer plays well with connection pools in a threaded web server.

We're still not using the REUSABLE strategy, but for compatibility are specifying `client_strategy=ldap3.SYNC`.

Can you suggest anything we might be able to do to restore compatibility in this environment?

**Comment by cannatag** [comment]
Does it correctly work with the 1.4.0 version in threaded server?

**Comment by cannatag** [comment]
By the way I'm reverting to SYNC in 2.1.1. REUSABLE works, but adds too much "magic" as a default selection.

**Comment by jaraco** [comment]
Yes, this server works flawlessly with 1.4.0, where we rely minute-by-minute on this service for several of our production-grade applications. Now that I again more closely at the traceback, the line references don't match what I would expect from our library, so it's possible that our wrapper around ldap3 isn't getting installed correctly, which may contradict my previous statement about using `client_strategy=ldap3.SYNC`. I'll investigate further.

**Comment by jaraco** [comment]
On further investigation, it seems I was improperly assessing the situation and was connecting to something running the stable version of ldap3 (1.4.0). Which is even more confusing because how on earth has it worked so reliably before? No matter, my report here is completely unfounded, and the actual error that's blocking our update is unrelated to this ticket, but instead appears to be related to the JSON serializability of the new result objects.

**Comment by jaraco** [comment]
As a matter of follow-up, the issue appears to be that where we were previously re-constructing the `attributes` of a `.response`, our adapting to ldap3 2.x meant we were using `response['attributes']` directly, but that object is a `CaseInsensitiveDict` which isn't JSON-serializable, so we'll need to wrap attributes before serializing them. I mention that here because I don't feel it represents an issue with ldap3, but just our usage of it.

**Comment by jaraco** [comment]
> how on earth has it worked so reliably before?

I think I now understand - I was testing against a staging version of our application which gets very little traffic, so the connections in the pool had probably died due to idle timeouts or similar and aren't being properly cleaned up.

**Comment by cannatag** [comment]
Thanks for letting me know. I tested ldap3 against a simple multithreaded program and it works without problems. I think that in your case the RESTARTABLE strategy could help. Alternatively you could send an Abandon(0) operation periodically that is a no-op that acts like a keep-alive operation.

Let me know if you need more help.
Bye
